# CMake generated Testfile for 
# Source directory: /home/yoar/votca/xtp/src/tests
# Build directory: /home/yoar/votca/xtp/xtp/src/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(unit_test_adiis "unit_test_adiis")
set_tests_properties(unit_test_adiis PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_aobasis "unit_test_aobasis")
set_tests_properties(unit_test_aobasis PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_aomatrix "unit_test_aomatrix")
set_tests_properties(unit_test_aomatrix PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_aomatrix3d "unit_test_aomatrix3d")
set_tests_properties(unit_test_aomatrix3d PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_aotransform "unit_test_aotransform")
set_tests_properties(unit_test_aotransform PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_aopotential "unit_test_aopotential")
set_tests_properties(unit_test_aopotential PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_atom "unit_test_atom")
set_tests_properties(unit_test_atom PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_basisset "unit_test_basisset")
set_tests_properties(unit_test_basisset PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_bfgs-trm "unit_test_bfgs-trm")
set_tests_properties(unit_test_bfgs-trm PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_bse "unit_test_bse")
set_tests_properties(unit_test_bse PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_bsecoupling "unit_test_bsecoupling")
set_tests_properties(unit_test_bsecoupling PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_bse_operator "unit_test_bse_operator")
set_tests_properties(unit_test_bse_operator PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_convergenceacc "unit_test_convergenceacc")
set_tests_properties(unit_test_convergenceacc PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_davidson "unit_test_davidson")
set_tests_properties(unit_test_davidson PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_dftcoupling "unit_test_dftcoupling")
set_tests_properties(unit_test_dftcoupling PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_dftengine "unit_test_dftengine")
set_tests_properties(unit_test_dftengine PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_diis "unit_test_diis")
set_tests_properties(unit_test_diis PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_dipoledipoleinteraction "unit_test_dipoledipoleinteraction")
set_tests_properties(unit_test_dipoledipoleinteraction PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_eeinteractor "unit_test_eeinteractor")
set_tests_properties(unit_test_eeinteractor PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_eigen "unit_test_eigen")
set_tests_properties(unit_test_eigen PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_eris "unit_test_eris")
set_tests_properties(unit_test_eris PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_espfit "unit_test_espfit")
set_tests_properties(unit_test_espfit PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_fourcenter "unit_test_fourcenter")
set_tests_properties(unit_test_fourcenter PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_gaussian "unit_test_gaussian")
set_tests_properties(unit_test_gaussian PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_glink "unit_test_glink")
set_tests_properties(unit_test_glink PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_gnode "unit_test_gnode")
set_tests_properties(unit_test_gnode PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_grid "unit_test_grid")
set_tests_properties(unit_test_grid PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_gw "unit_test_gw")
set_tests_properties(unit_test_gw PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_hdf5 "unit_test_hdf5")
set_tests_properties(unit_test_hdf5 PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_hist "unit_test_hist")
set_tests_properties(unit_test_hist PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_jobtopology "unit_test_jobtopology")
set_tests_properties(unit_test_jobtopology PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_numericalintegration "unit_test_numericalintegration")
set_tests_properties(unit_test_numericalintegration PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_nwchem "unit_test_nwchem")
set_tests_properties(unit_test_nwchem PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_orbitals "unit_test_orbitals")
set_tests_properties(unit_test_orbitals PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_orca "unit_test_orca")
set_tests_properties(unit_test_orca PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_polarsegment "unit_test_polarsegment")
set_tests_properties(unit_test_polarsegment PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_polarsite "unit_test_polarsite")
set_tests_properties(unit_test_polarsite PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_populationanalysis "unit_test_populationanalysis")
set_tests_properties(unit_test_populationanalysis PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_ppm "unit_test_ppm")
set_tests_properties(unit_test_ppm PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_qmatom "unit_test_qmatom")
set_tests_properties(unit_test_qmatom PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_qmfragment "unit_test_qmfragment")
set_tests_properties(unit_test_qmfragment PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_qmmolecule "unit_test_qmmolecule")
set_tests_properties(unit_test_qmmolecule PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_qmnblist "unit_test_qmnblist")
set_tests_properties(unit_test_qmnblist PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_qmpair "unit_test_qmpair")
set_tests_properties(unit_test_qmpair PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_qmstate "unit_test_qmstate")
set_tests_properties(unit_test_qmstate PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_radial_euler_maclaurin_rule "unit_test_radial_euler_maclaurin_rule")
set_tests_properties(unit_test_radial_euler_maclaurin_rule PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_rate_engine "unit_test_rate_engine")
set_tests_properties(unit_test_rate_engine PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_rpa "unit_test_rpa")
set_tests_properties(unit_test_rpa PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_rpa_eigenvalues "unit_test_rpa_eigenvalues")
set_tests_properties(unit_test_rpa_eigenvalues PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_segment "unit_test_segment")
set_tests_properties(unit_test_segment PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_aoshell "unit_test_aoshell")
set_tests_properties(unit_test_aoshell PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_segmentmapper "unit_test_segmentmapper")
set_tests_properties(unit_test_segmentmapper PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_sigma_exact "unit_test_sigma_exact")
set_tests_properties(unit_test_sigma_exact PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_sigma_ppm "unit_test_sigma_ppm")
set_tests_properties(unit_test_sigma_ppm PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_sphere_lebedev_rule "unit_test_sphere_lebedev_rule")
set_tests_properties(unit_test_sphere_lebedev_rule PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_sphere_lebedev_rule_fine "unit_test_sphere_lebedev_rule_fine")
set_tests_properties(unit_test_sphere_lebedev_rule_fine PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_sphere_lebedev_rule_xfine "unit_test_sphere_lebedev_rule_xfine")
set_tests_properties(unit_test_sphere_lebedev_rule_xfine PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_statetracker "unit_test_statetracker")
set_tests_properties(unit_test_statetracker PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_symmetric_matrix "unit_test_symmetric_matrix")
set_tests_properties(unit_test_symmetric_matrix PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_threecenter_dft "unit_test_threecenter_dft")
set_tests_properties(unit_test_threecenter_dft PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_threecenter_gwbse "unit_test_threecenter_gwbse")
set_tests_properties(unit_test_threecenter_gwbse PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_topology "unit_test_topology")
set_tests_properties(unit_test_topology PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_trustregion "unit_test_trustregion")
set_tests_properties(unit_test_trustregion PROPERTIES  LABELS "xtp;votca;unit")
add_test(unit_test_vc2index "unit_test_vc2index")
set_tests_properties(unit_test_vc2index PROPERTIES  LABELS "xtp;votca;unit")
