# CMake generated Testfile for 
# Source directory: /home/yoar/votca/tools/src/tests
# Build directory: /home/yoar/votca/xtp/tools/src/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(unit_test_constants "unit_test_constants")
set_tests_properties(unit_test_constants PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_correlate "unit_test_correlate")
set_tests_properties(unit_test_correlate PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_crosscorrelate "unit_test_crosscorrelate")
set_tests_properties(unit_test_crosscorrelate PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_cubicspline "unit_test_cubicspline")
set_tests_properties(unit_test_cubicspline PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_datacollection "unit_test_datacollection")
set_tests_properties(unit_test_datacollection PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_edge_base "unit_test_edge_base")
set_tests_properties(unit_test_edge_base PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_edgecontainer "unit_test_edgecontainer")
set_tests_properties(unit_test_edgecontainer PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_elements "unit_test_elements")
set_tests_properties(unit_test_elements PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_filesystem "unit_test_filesystem")
set_tests_properties(unit_test_filesystem PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_floatingpointcomparison "unit_test_floatingpointcomparison")
set_tests_properties(unit_test_floatingpointcomparison PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_graphalgorithm "unit_test_graphalgorithm")
set_tests_properties(unit_test_graphalgorithm PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_graph_base "unit_test_graph_base")
set_tests_properties(unit_test_graph_base PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_graph_bf_visitor "unit_test_graph_bf_visitor")
set_tests_properties(unit_test_graph_bf_visitor PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_graph_df_visitor "unit_test_graph_df_visitor")
set_tests_properties(unit_test_graph_df_visitor PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_graphdistvisitor "unit_test_graphdistvisitor")
set_tests_properties(unit_test_graphdistvisitor PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_graphnode "unit_test_graphnode")
set_tests_properties(unit_test_graphnode PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_graphvisitor "unit_test_graphvisitor")
set_tests_properties(unit_test_graphvisitor PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_histogramnew "unit_test_histogramnew")
set_tests_properties(unit_test_histogramnew PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_identity "unit_test_identity")
set_tests_properties(unit_test_identity PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_linalg "unit_test_linalg")
set_tests_properties(unit_test_linalg PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_name "unit_test_name")
set_tests_properties(unit_test_name PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_property "unit_test_property")
set_tests_properties(unit_test_property PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_reducededge "unit_test_reducededge")
set_tests_properties(unit_test_reducededge PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_reducedgraph "unit_test_reducedgraph")
set_tests_properties(unit_test_reducedgraph PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_structureparameters "unit_test_structureparameters")
set_tests_properties(unit_test_structureparameters PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_table "unit_test_table")
set_tests_properties(unit_test_table PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_thread "unit_test_thread")
set_tests_properties(unit_test_thread PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_tokenizer "unit_test_tokenizer")
set_tests_properties(unit_test_tokenizer PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_random "unit_test_random")
set_tests_properties(unit_test_random PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_akimaspline "unit_test_akimaspline")
set_tests_properties(unit_test_akimaspline PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_linspline "unit_test_linspline")
set_tests_properties(unit_test_linspline PROPERTIES  LABELS "tools;votca;unit")
add_test(unit_test_unitconverter "unit_test_unitconverter")
set_tests_properties(unit_test_unitconverter PROPERTIES  LABELS "tools;votca;unit")
