#the original source of this file can be found in tools repository change it ther
# changes in tools|csg tiggered a full rebuild
# changes in csgapps|csg-manual|csg-tutorials only trigger tools+csg+ifself

language: cpp

sudo: false

addons:
  apt:
    sources:
      - boost-latest 
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - ccache
      - gcc-4.8
      - g++-4.8
      - libfftw3-dev
      - cmake
      - cmake-data
      - libgsl0-dev
      - txt2tags
      - libboost1.55-all-dev
      - libexpat1-dev
      - libsqlite3-dev
      - libhdf5-serial-dev
      - pkg-config
      - pgf
      - python-lxml
      - texlive-fonts-recommended
      - texlive-latex-extra
      - texlive-latex-recommended
      - cm-super
      - texlive-humanities
      - texlive-pstricks
      - texlive-latex3
      - transfig
      - inkscape
      - doxygen
      - graphviz
      - python-numpy
      - gnuplot-nox
      - octave

env:
  global:
    - HDF5_VERSION=1.8.18
    - GMX_MAX_THREADS=8
    - CCACHE_CPP2=yes #for clang
    - GVER=4.8
  matrix: #NINJA=1 is currently not support by Travis' cmake, enable when >=2.8.9
    - XTP=yes WERROR=yes J=4 TYPE=Release
    - XTP=yes WALL=yes J=4 XTP_MAN=yes TYPE=Release
    - XTP=yes WERROR=yes J=4 BDIR=build TYPE=Debug
    - XTP=yes WALL=yes J=4 BDIR=build TYPE=Debug

before_script:
  - rm -vrf * .git
  - wget https://raw.githubusercontent.com/votca/buildutil/master/build.sh && chmod 755 build.sh
  - mkdir -p "$HOME/votca/src"
  - if [[ ${MINIMAL} != yes ]]; then 
      wget -qO- https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-${HDF5_VERSION%.*}/hdf5-${HDF5_VERSION}/src/hdf5-${HDF5_VERSION}.tar.gz | tar -xz &&
      cd hdf5-${HDF5_VERSION} && ./configure --prefix=$HOME/hdf5 && make -j4 &> /dev/null && make install && cd ..;
    fi
  - if [[ ${XTP_MAN} ]]; then git clone --depth=1 https://github.com/votca/doxygen.git "$HOME/votca/src/devdoc"; fi 
  - if [[ ${GVER} ]]; then export CC=gcc-${GVER}; export CXX=g++-${GVER}; fi

script:
  - PATH="$HOME/hdf5:$PATH" ./build.sh -Wu $([[ ${TRAVIS_BRANCH} = stable ]] || echo "--dev") --prefix "$HOME/votca"
    ${TYPE:+-DCMAKE_BUILD_TYPE=${TYPE}} ${XTP_MAN:+--build-manual}
    ${TEST:+--runtest=$TEST} ${WERROR:+--warn-to-errors} -DWITH_H5MD=ON ${MINIMAL:+--minimal} ${MAN:+--devdoc}
    ${J:+-j$J} ${BDIR:+--builddir=$BDIR} ${NINJA:+--ninja} ${WALL:+--Wall} ${GMX_VERSION:+--gmx-release ${GMX_VERSION}}
    --directory "$HOME/votca/src" --no-clean --depth 1 -DGMX_USE_RDTSCP=OFF ${GMX_DOUBLE:+-DGMX_DOUBLE=yes}
    tools $([[ ${MINIMAL} ]] || echo gromacs) csg csgapps ${MAN:+csg-manual} ${TEST:+csg-tutorials}
    ${CTP:+moo ctp} ${XTP:+moo ctp xtp}

after_success:
  - if [[ ${XTP_MAN} ]]; then
      cp "$HOME"/votca/{share/votca/manual,src/devdoc}/xtp-manual.pdf;
      cd "$HOME/votca/src/devdoc";
      if [[ ${TRAVIS_BRANCH} = master && ${encrypted_f4232b15402f_key} && ${encrypted_f4232b15402f_iv} && ${TRAVIS_PULL_REQUEST} == false ]]; then
        git config --global user.name "Automatic Deployment (Travis CI)";
        git config --global user.email "votca-commits@googlegroups.com";
        git add --all && git commit -m "XTP Documentation Update";
        openssl aes-256-cbc -K $encrypted_f4232b15402f_key -iv $encrypted_f4232b15402f_iv -in deploy2.enc -out ~/.ssh/id_rsa -d;
        chmod 600 ~/.ssh/id_rsa;
        git push git@github.com:votca/doxygen.git gh-pages;
      else
        git status
        git diff --no-color | head -n 500;
      fi;
    fi

cache:
  - ccache

compiler:
  - gcc

notifications:
  email:
    - votca-commits@googlegroups.com 
