# CMake generated Testfile for 
# Source directory: /home/yoar/votca/csg/src/tests
# Build directory: /home/yoar/votca/xtp/csg/src/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(unit_test_bead "unit_test_bead")
set_tests_properties(unit_test_bead PROPERTIES  LABELS "csg;votca;unit")
add_test(unit_test_beadtriple "unit_test_beadtriple")
set_tests_properties(unit_test_beadtriple PROPERTIES  LABELS "csg;votca;unit")
add_test(unit_test_basebead "unit_test_basebead")
set_tests_properties(unit_test_basebead PROPERTIES  LABELS "csg;votca;unit")
add_test(unit_test_beadmotif_algorithms "unit_test_beadmotif_algorithms")
set_tests_properties(unit_test_beadmotif_algorithms PROPERTIES  LABELS "csg;votca;unit")
add_test(unit_test_beadmotif_base "unit_test_beadmotif_base")
set_tests_properties(unit_test_beadmotif_base PROPERTIES  LABELS "csg;votca;unit")
add_test(unit_test_beadmotif_connector "unit_test_beadmotif_connector")
set_tests_properties(unit_test_beadmotif_connector PROPERTIES  LABELS "csg;votca;unit")
add_test(unit_test_beadstructure_base "unit_test_beadstructure_base")
set_tests_properties(unit_test_beadstructure_base PROPERTIES  LABELS "csg;votca;unit")
add_test(unit_test_beadstructure_algorithms "unit_test_beadstructure_algorithms")
set_tests_properties(unit_test_beadstructure_algorithms PROPERTIES  LABELS "csg;votca;unit")
add_test(unit_test_bondedstatistics "unit_test_bondedstatistics")
set_tests_properties(unit_test_bondedstatistics PROPERTIES  LABELS "csg;votca;unit")
add_test(unit_test_csg_topology "unit_test_csg_topology")
set_tests_properties(unit_test_csg_topology PROPERTIES  LABELS "csg;votca;unit")
add_test(unit_test_interaction "unit_test_interaction")
set_tests_properties(unit_test_interaction PROPERTIES  LABELS "csg;votca;unit")
add_test(unit_test_lammpsdatareader "unit_test_lammpsdatareader")
set_tests_properties(unit_test_lammpsdatareader PROPERTIES  LABELS "csg;votca;unit")
add_test(unit_test_lammpsdumpreaderwriter "unit_test_lammpsdumpreaderwriter")
set_tests_properties(unit_test_lammpsdumpreaderwriter PROPERTIES  LABELS "csg;votca;unit")
add_test(unit_test_nblist_3body "unit_test_nblist_3body")
set_tests_properties(unit_test_nblist_3body PROPERTIES  LABELS "csg;votca;unit")
add_test(unit_test_nblistgrid_3body "unit_test_nblistgrid_3body")
set_tests_properties(unit_test_nblistgrid_3body PROPERTIES  LABELS "csg;votca;unit")
add_test(unit_test_pdbreader "unit_test_pdbreader")
set_tests_properties(unit_test_pdbreader PROPERTIES  LABELS "csg;votca;unit")
add_test(unit_test_tabulatedpotential "unit_test_tabulatedpotential")
set_tests_properties(unit_test_tabulatedpotential PROPERTIES  LABELS "csg;votca;unit")
add_test(unit_test_triplelist "unit_test_triplelist")
set_tests_properties(unit_test_triplelist PROPERTIES  LABELS "csg;votca;unit")
