.TH "csg_imc_solve" 1 "2019-11-11 18:11:01" "Version: 1.6-dev gitid: 6a013c6 (dirty)"


.SH NAME

.P
csg_imc_solve \- Part of the VOTCA package

.SH SYNOPSIS

.P
\fBcsg_imc_solve\fR [\fIOPTION\fR] [\fIOPTIONPARAMETERS\fR]

.SH DESCRIPTION

.P
Solves the linear system for IMCs

.P
Please visit the program site at __http://www.votca.org__.

.SH OPTIONS

.P
Allowed options:

.TP
\fB\-h [ \-\-help ]\fR
display this help and exit
.TP
\fB\-v [ \-\-verbose ]\fR
be loud and noisy
.TP
\fB\-r [ \-\-regularization ] arg (=0)\fR
regularization factor
.TP
\fB\-i [ \-\-imcfile ] arg\fR
imc statefile
.TP
\fB\-g [ \-\-gmcfile ] arg\fR
gmc statefile
.TP
\fB\-n [ \-\-idxfile ] arg\fR
idx statefile

.SH AUTHORS

.P
Written and maintained by the VOTCA Development Team <devs@votca.org>

.P
This Manual Page was converted from t2t format to the this format by txt2tags (http://txt2tags.org) !
The t2t file was extracted from 'csg_imc_solve \-\-help' by help2t2t (version 1.6\-dev gitid: 6a013c6 (dirty))

.SH COPYRIGHT

.P
Copyright 2009\-2011 The VOTCA Development Team (http://www.votca.org)

.P
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

.P
    http://www.apache.org/licenses/LICENSE\-2.0

.P
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

.\" man code generated by txt2tags 2.6 (http://txt2tags.org)
.\" cmdline: txt2tags -q -t man -i csg_imc_solve.t2t -o csg_imc_solve.man
