.TH "csg_fmatch" 1 "2019-11-11 18:11:01" "Version: 1.6-dev gitid: 6a013c6 (dirty)"


.SH NAME

.P
csg_fmatch \- Part of the VOTCA package

.SH SYNOPSIS

.P
\fBcsg_fmatch\fR [\fIOPTION\fR] [\fIOPTIONPARAMETERS\fR]

.SH DESCRIPTION

.P
Perform force matching (also called multiscale coarse\-graining)

.P
Please visit the program site at __http://www.votca.org__.

.SH OPTIONS

.P
Allowed options:

.TP
\fB\-h [ \-\-help ]\fR
display this help and exit
.TP
\fB\-v [ \-\-verbose ]\fR
be loud and noisy
.TP
\fB\-\-top arg\fR
atomistic topology file
.TP
\fB\-\-options arg\fR
options file for coarse graining
.TP
\fB\-\-trj\-force arg\fR
coarse\-grained trajectory containing forces of
already known interactions

.P
Mapping options:

.TP
\fB\-\-cg arg\fR
coarse graining mapping and bond definitions
(xml\-file)
.TP
\fB\-\-map\-ignore arg\fR
list of molecules to ignore separated by ;
.TP
\fB\-\-no\-map\fR
disable mapping and act on original trajectory

.P
Trajectory options:

.TP
\fB\-\-trj arg\fR
atomistic trajectory file
.TP
\fB\-\-begin arg (=0)\fR
skip frames before this time (only works for
Gromacs files)
.TP
\fB\-\-first\-frame arg (=0)\fR
start with this frame
.TP
\fB\-\-nframes arg\fR
process the given number of frames

.SH AUTHORS

.P
Written and maintained by the VOTCA Development Team <devs@votca.org>

.P
This Manual Page was converted from t2t format to the this format by txt2tags (http://txt2tags.org) !
The t2t file was extracted from 'csg_fmatch \-\-help' by help2t2t (version 1.6\-dev gitid: 6a013c6 (dirty))

.SH COPYRIGHT

.P
Copyright 2009\-2011 The VOTCA Development Team (http://www.votca.org)

.P
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

.P
    http://www.apache.org/licenses/LICENSE\-2.0

.P
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

.\" man code generated by txt2tags 2.6 (http://txt2tags.org)
.\" cmdline: txt2tags -q -t man -i csg_fmatch.t2t -o csg_fmatch.man
