# CMake generated Testfile for 
# Source directory: /home/yoar/votca/csg/src/tools
# Build directory: /home/yoar/votca/xtp/csg/src/tools
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(integration_csg_reupdateHelp "csg_reupdate" "--help")
set_tests_properties(integration_csg_reupdateHelp PROPERTIES  LABELS "csg;tools;votca;integration")
add_test(integration_csg_mapHelp "csg_map" "--help")
set_tests_properties(integration_csg_mapHelp PROPERTIES  LABELS "csg;tools;votca;integration")
add_test(integration_csg_dumpHelp "csg_dump" "--help")
set_tests_properties(integration_csg_dumpHelp PROPERTIES  LABELS "csg;tools;votca;integration")
add_test(integration_csg_propertyHelp "csg_property" "--help")
set_tests_properties(integration_csg_propertyHelp PROPERTIES  LABELS "csg;tools;votca;integration")
add_test(integration_csg_resampleHelp "csg_resample" "--help")
set_tests_properties(integration_csg_resampleHelp PROPERTIES  LABELS "csg;tools;votca;integration")
add_test(integration_csg_statHelp "csg_stat" "--help")
set_tests_properties(integration_csg_statHelp PROPERTIES  LABELS "csg;tools;votca;integration")
add_test(integration_csg_fmatchHelp "csg_fmatch" "--help")
set_tests_properties(integration_csg_fmatchHelp PROPERTIES  LABELS "csg;tools;votca;integration")
add_test(integration_csg_gmxtopolHelp "csg_gmxtopol" "--help")
set_tests_properties(integration_csg_gmxtopolHelp PROPERTIES  LABELS "csg;tools;votca;integration")
add_test(integration_csg_dlptopolHelp "csg_dlptopol" "--help")
set_tests_properties(integration_csg_dlptopolHelp PROPERTIES  LABELS "csg;tools;votca;integration")
add_test(integration_csg_densityHelp "csg_density" "--help")
set_tests_properties(integration_csg_densityHelp PROPERTIES  LABELS "csg;tools;votca;integration")
add_test(integration_csg_imc_solveHelp "csg_imc_solve" "--help")
set_tests_properties(integration_csg_imc_solveHelp PROPERTIES  LABELS "csg;tools;votca;integration")
add_test(integration_Run_csg_reupdate "/home/yoar/votca/xtp/csg/src/tools/csg_reupdate" "--gentable" "true" "--options" "/home/yoar/votca/csg/src/tools/references/spce/settings_re.xml")
set_tests_properties(integration_Run_csg_reupdate PROPERTIES  LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_reupdate")
add_test(integration_Compare_csg_reupdate_output "/home/yoar/votca/xtp/tools/scripts/votca_compare" "--etol" "5e-5" "-f1" "CG-CG.pot.new" "-f2" "/home/yoar/votca/csg/src/tools/references/spce/CG-CG.pot.re")
set_tests_properties(integration_Compare_csg_reupdate_output PROPERTIES  DEPENDS "integration_Run_csg_reupdate" LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_reupdate")
add_test(integration_Run_csg_fmatch "/home/yoar/votca/xtp/csg/src/tools/csg_fmatch" "--top" "/home/yoar/votca/csg/src/tools/references/spce/topol.xml" "--trj" "/home/yoar/votca/csg/src/tools/references/spce/frame.dump" "--options" "/home/yoar/votca/csg/src/tools/references/spce/settings_fmatch.xml" "--cg" "/home/yoar/votca/csg/src/tools/references/spce/mapping.xml")
set_tests_properties(integration_Run_csg_fmatch PROPERTIES  LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_fmatch")
add_test(integration_Compare_csg_fmatch_output "/home/yoar/votca/xtp/tools/scripts/votca_compare" "--etol" "5e-5" "-f1" "CG-CG.force" "-f2" "/home/yoar/votca/csg/src/tools/references/spce/CG-CG.force.fmatch")
set_tests_properties(integration_Compare_csg_fmatch_output PROPERTIES  DEPENDS "integration_Run_csg_fmatch" LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_fmatch")
add_test(integration_Run_csg_fmatch_3body "/home/yoar/votca/xtp/csg/src/tools/csg_fmatch" "--top" "/home/yoar/votca/csg/src/tools/references/spce/topol.xml" "--trj" "/home/yoar/votca/csg/src/tools/references/spce/frame.dump" "--options" "/home/yoar/votca/csg/src/tools/references/spce/settings_fmatch_3body.xml" "--cg" "/home/yoar/votca/csg/src/tools/references/spce/mapping.xml")
set_tests_properties(integration_Run_csg_fmatch_3body PROPERTIES  LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_fmatch_3body")
add_test(integration_Compare_csg_fmatch_3body_output1 "/home/yoar/votca/xtp/tools/scripts/votca_compare" "--etol" "5e-5" "-f1" "CG-CG.force" "-f2" "/home/yoar/votca/csg/src/tools/references/spce/CG-CG.force.fmatch_3body")
set_tests_properties(integration_Compare_csg_fmatch_3body_output1 PROPERTIES  DEPENDS "integration_Run_csg_fmatch" LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_fmatch_3body")
add_test(integration_Compare_csg_fmatch_3body_output2 "/home/yoar/votca/xtp/tools/scripts/votca_compare" "--etol" "5e-5" "-f1" "CG-CG-CG.force" "-f2" "/home/yoar/votca/csg/src/tools/references/spce/CG-CG-CG.force.fmatch_3body")
set_tests_properties(integration_Compare_csg_fmatch_3body_output2 PROPERTIES  DEPENDS "integration_Run_csg_fmatch" LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_fmatch_3body")
add_test(integration_Compare_csg_fmatch_3body_output3 "/home/yoar/votca/xtp/tools/scripts/votca_compare" "--etol" "5e-5" "-f1" "CG-CG-CG.pot" "-f2" "/home/yoar/votca/csg/src/tools/references/spce/CG-CG-CG.pot.fmatch_3body")
set_tests_properties(integration_Compare_csg_fmatch_3body_output3 PROPERTIES  DEPENDS "integration_Run_csg_fmatch" LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_fmatch_3body")
add_test(integration_Run_csg_map "/home/yoar/votca/xtp/csg/src/tools/csg_map" "--top" "/home/yoar/votca/csg/src/tools/references/spce/topol.xml" "--trj" "/home/yoar/votca/csg/src/tools/references/spce/frame.dump" "--out" "frame.dump" "--no-map" "--force")
set_tests_properties(integration_Run_csg_map PROPERTIES  LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_map")
add_test(integration_Compare_csg_map_output "/home/yoar/votca/xtp/tools/scripts/votca_compare" "--etol" "5e-5" "-f1" "frame.dump" "-f2" "/home/yoar/votca/csg/src/tools/references/spce/frame.dump")
set_tests_properties(integration_Compare_csg_map_output PROPERTIES  DEPENDS "integration_Run_csg_map" LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_map")
add_test(integration_Run_csg_stat "/home/yoar/votca/xtp/csg/src/tools/csg_stat" "--top" "/home/yoar/votca/csg/src/tools/references/spce/topol.xml" "--trj" "/home/yoar/votca/csg/src/tools/references/spce/frame.dump" "--options" "/home/yoar/votca/csg/src/tools/references/spce/settings_rdf.xml" "--cg" "/home/yoar/votca/csg/src/tools/references/spce/mapping.xml")
set_tests_properties(integration_Run_csg_stat PROPERTIES  LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_stat")
add_test(integration_Compare_csg_stat_output1 "/home/yoar/votca/xtp/tools/scripts/votca_compare" "--etol" "5e-5" "-f1" "CG-CG.dist.new" "-f2" "/home/yoar/votca/csg/src/tools/references/spce/CG-CG.rdf")
set_tests_properties(integration_Compare_csg_stat_output1 PROPERTIES  DEPENDS "integration_Run_csg_stat" LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_stat")
add_test(integration_Compare_csg_stat_output2 "/home/yoar/votca/xtp/tools/scripts/votca_compare" "--etol" "5e-5" "-f1" "CG-CG.force.new" "-f2" "/home/yoar/votca/csg/src/tools/references/spce/CG-CG.pmf")
set_tests_properties(integration_Compare_csg_stat_output2 PROPERTIES  DEPENDS "integration_Run_csg_stat" LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_stat")
add_test(integration_Run_csg_stat_angular "/home/yoar/votca/xtp/csg/src/tools/csg_stat" "--top" "/home/yoar/votca/csg/src/tools/references/spce/topol.xml" "--trj" "/home/yoar/votca/csg/src/tools/references/spce/frame.dump" "--options" "/home/yoar/votca/csg/src/tools/references/spce/settings_angular.xml" "--cg" "/home/yoar/votca/csg/src/tools/references/spce/mapping.xml")
set_tests_properties(integration_Run_csg_stat_angular PROPERTIES  LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_stat_angular")
add_test(integration_Compare_csg_stat_angular_output "/home/yoar/votca/xtp/tools/scripts/votca_compare" "--etol" "5e-5" "-f1" "CG-CG-CG.dist.new" "-f2" "/home/yoar/votca/csg/src/tools/references/spce/CG-CG-CG.angular")
set_tests_properties(integration_Compare_csg_stat_angular_output PROPERTIES  DEPENDS "integration_Run_csg_stat_angular" LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_stat_angular")
add_test(integration_Run_csg_stat-imc "/home/yoar/votca/xtp/csg/src/tools/csg_stat" "--top" "/home/yoar/votca/csg/src/tools/references/spce/topol.xml" "--trj" "/home/yoar/votca/csg/src/tools/references/spce/frame.dump" "--do-imc" "--options" "/home/yoar/votca/csg/src/tools/references/spce/settings_imc.xml" "--cg" "/home/yoar/votca/csg/src/tools/references/spce/mapping.xml")
set_tests_properties(integration_Run_csg_stat-imc PROPERTIES  LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_stat-imc")
add_test(integration_Compare_csg_stat-imc_output "/home/yoar/votca/xtp/tools/scripts/votca_compare" "--etol" "5e-5" "-f1" "CG-CG.imc" "-f2" "/home/yoar/votca/csg/src/tools/references/spce/CG-CG.imc")
set_tests_properties(integration_Compare_csg_stat-imc_output PROPERTIES  DEPENDS "integration_Run_csg_stat-imc" LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_stat-imc")
add_test(integration_Compare_csg_stat-imc_output_2 "/home/yoar/votca/xtp/tools/scripts/votca_compare" "--etol" "5e-5" "-f1" "CG-CG.dist.new" "-f2" "/home/yoar/votca/csg/src/tools/references/spce/CG-CG.dist.imc")
set_tests_properties(integration_Compare_csg_stat-imc_output_2 PROPERTIES  DEPENDS "integration_Run_csg_stat-imc" LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_stat-imc")
add_test(integration_Compare_csg_stat-imc_output_3 "/home/yoar/votca/xtp/tools/scripts/votca_compare" "--etol" "5e-5" "-f1" "CG-CG.gmc" "-f2" "/home/yoar/votca/csg/src/tools/references/spce/CG-CG.gmc")
set_tests_properties(integration_Compare_csg_stat-imc_output_3 PROPERTIES  DEPENDS "integration_Run_csg_stat-imc" LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_stat-imc")
add_test(integration_Compare_csg_stat-imc_output_4 "/usr/bin/cmake" "-E" "compare_files" "CG-CG.idx" "/home/yoar/votca/csg/src/tools/references/spce/CG-CG.idx")
set_tests_properties(integration_Compare_csg_stat-imc_output_4 PROPERTIES  DEPENDS "integration_Run_csg_stat-imc" LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_stat-imc")
add_test(integration_Run_csg_imc_solve "/home/yoar/votca/xtp/csg/src/tools/csg_imc_solve" "-i" "/home/yoar/votca/csg/src/tools/references/spce/imc/CG-CG.imc" "-g" "/home/yoar/votca/csg/src/tools/references/spce/imc/CG-CG.gmc" "-n" "/home/yoar/votca/csg/src/tools/references/spce/imc/CG-CG.idx")
set_tests_properties(integration_Run_csg_imc_solve PROPERTIES  LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_imc_solve")
add_test(integration_Compare_csg_imc_solve_output "/home/yoar/votca/xtp/tools/scripts/votca_compare" "--etol" "5e-5" "-f1" "CG-CG.dpot.imc" "-f2" "/home/yoar/votca/csg/src/tools/references/spce/imc/CG-CG.dpot.imc")
set_tests_properties(integration_Compare_csg_imc_solve_output PROPERTIES  DEPENDS "integration_Run_csg_imc_solve" LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_imc_solve")
add_test(integration_Run_csg_imc_solve_reg "/home/yoar/votca/xtp/csg/src/tools/csg_imc_solve" "-r" "1000" "-i" "/home/yoar/votca/csg/src/tools/references/LJ1-LJ2/group_1.imc" "-g" "/home/yoar/votca/csg/src/tools/references/LJ1-LJ2/group_1.gmc" "-n" "/home/yoar/votca/csg/src/tools/references/LJ1-LJ2/group_1.idx")
set_tests_properties(integration_Run_csg_imc_solve_reg PROPERTIES  LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_imc_solve_reg")
add_test(integration_Compare_csg_imc_solve_reg_output_2 "/home/yoar/votca/xtp/tools/scripts/votca_compare" "--etol" "5e-5" "-f1" "LJ1-LJ1.dpot.imc" "-f2" "/home/yoar/votca/csg/src/tools/references/LJ1-LJ2/LJ1-LJ1.dpot.imc")
set_tests_properties(integration_Compare_csg_imc_solve_reg_output_2 PROPERTIES  DEPENDS "integration_Run_csg_imc_solve_reg" LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_imc_solve_reg")
add_test(integration_Compare_csg_imc_solve_reg_output_3 "/home/yoar/votca/xtp/tools/scripts/votca_compare" "--etol" "5e-5" "-f1" "LJ1-LJ2.dpot.imc" "-f2" "/home/yoar/votca/csg/src/tools/references/LJ1-LJ2/LJ1-LJ2.dpot.imc")
set_tests_properties(integration_Compare_csg_imc_solve_reg_output_3 PROPERTIES  DEPENDS "integration_Run_csg_imc_solve_reg" LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_imc_solve_reg")
add_test(integration_Compare_csg_imc_solve_reg_output_4 "/home/yoar/votca/xtp/tools/scripts/votca_compare" "--etol" "5e-5" "-f1" "LJ2-LJ2.dpot.imc" "-f2" "/home/yoar/votca/csg/src/tools/references/LJ1-LJ2/LJ2-LJ2.dpot.imc")
set_tests_properties(integration_Compare_csg_imc_solve_reg_output_4 PROPERTIES  DEPENDS "integration_Run_csg_imc_solve_reg" LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_imc_solve_reg")
add_test(integration_Run_csg_resample_akima "/home/yoar/votca/xtp/csg/src/tools/csg_resample" "--in" "/home/yoar/votca/csg/src/tools/references/csg_resample/table_in" "--out" "table_akima" "--type" "akima" "--grid" "0:0.1:3")
set_tests_properties(integration_Run_csg_resample_akima PROPERTIES  LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_resample")
add_test(integration_Compare_csg_resample_akima_output "/home/yoar/votca/xtp/tools/scripts/votca_compare" "--etol" "5e-5" "-f1" "table_akima" "-f2" "/home/yoar/votca/csg/src/tools/references/csg_resample/table_akima")
set_tests_properties(integration_Compare_csg_resample_akima_output PROPERTIES  DEPENDS "integration_Run_csg_resample_akima" LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_resample")
add_test(integration_Run_csg_resample_cubic "/home/yoar/votca/xtp/csg/src/tools/csg_resample" "--in" "/home/yoar/votca/csg/src/tools/references/csg_resample/table_in" "--out" "table_cubic" "--type" "cubic" "--grid" "0:0.1:3")
set_tests_properties(integration_Run_csg_resample_cubic PROPERTIES  LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_resample")
add_test(integration_Compare_csg_resample_cubic_output "/home/yoar/votca/xtp/tools/scripts/votca_compare" "--etol" "5e-5" "-f1" "table_cubic" "-f2" "/home/yoar/votca/csg/src/tools/references/csg_resample/table_cubic")
set_tests_properties(integration_Compare_csg_resample_cubic_output PROPERTIES  DEPENDS "integration_Run_csg_resample_cubic" LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_resample")
add_test(integration_Run_csg_resample_linear "/home/yoar/votca/xtp/csg/src/tools/csg_resample" "--in" "/home/yoar/votca/csg/src/tools/references/csg_resample/table_in" "--out" "table_linear" "--type" "linear" "--grid" "0:0.1:3")
set_tests_properties(integration_Run_csg_resample_linear PROPERTIES  LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_resample")
add_test(integration_Compare_csg_resample_linear_output "/home/yoar/votca/xtp/tools/scripts/votca_compare" "--etol" "5e-5" "-f1" "table_linear" "-f2" "/home/yoar/votca/csg/src/tools/references/csg_resample/table_linear")
set_tests_properties(integration_Compare_csg_resample_linear_output PROPERTIES  DEPENDS "integration_Run_csg_resample_linear" LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_resample")
add_test(integration_Run_csg_resample_cubicfit "/home/yoar/votca/xtp/csg/src/tools/csg_resample" "--in" "/home/yoar/votca/csg/src/tools/references/csg_resample/table_in" "--out" "table_cubicfit" "--type" "cubic" "--grid" "0:1:9" "--fitgrid" "0:2:9")
set_tests_properties(integration_Run_csg_resample_cubicfit PROPERTIES  LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_resample")
add_test(integration_Compare_csg_resample_cubicfit_output "/home/yoar/votca/xtp/tools/scripts/votca_compare" "--etol" "5e-5" "-f1" "table_cubicfit" "-f2" "/home/yoar/votca/csg/src/tools/references/csg_resample/table_cubicfit")
set_tests_properties(integration_Compare_csg_resample_cubicfit_output PROPERTIES  DEPENDS "integration_Run_csg_resample_cubicfit" LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_resample")
add_test(integration_Run_csg_dump "/bin/bash" "-c" "/home/yoar/votca/xtp/csg/src/tools/csg_dump --top /home/yoar/votca/csg/src/tools/references/methanol-water//topol_cg.xml > csg_dump.out")
set_tests_properties(integration_Run_csg_dump PROPERTIES  LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_dump")
add_test(integration_Compare_csg_dump_output "/usr/bin/cmake" "-E" "compare_files" "csg_dump.out" "/home/yoar/votca/csg/src/tools/references/methanol-water//csg_dump.out")
set_tests_properties(integration_Compare_csg_dump_output PROPERTIES  DEPENDS "integration_Run_csg_dump" LABELS "csg;tools;votca;integration" WORKING_DIRECTORY "/home/yoar/votca/xtp/csg/src/tools/Run_csg_dump")
