include(CMakeFindDependencyMacro)
find_dependency(Eigen3 NO_MODULE)
find_dependency(Boost 1.53.0 COMPONENTS program_options)
find_dependency(VOTCA_TOOLS NO_MODULE)
include("${CMAKE_CURRENT_LIST_DIR}/VOTCA_CSG_Targets.cmake")
add_executable(VOTCA::csg_inverse IMPORTED)
set_property(TARGET VOTCA::csg_inverse PROPERTY IMPORTED_LOCATION "/home/yoar/votca/xtp/votca/bin/csg_inverse")
set_target_properties(VOTCA::csg_inverse PROPERTIES VOTCA_CSG_DEFAULTS "/home/yoar/votca/xtp/votca/share/votca/xml/csg_defaults.xml")
add_executable(VOTCA::csg_call IMPORTED)
set_property(TARGET VOTCA::csg_call PROPERTY IMPORTED_LOCATION "/home/yoar/votca/xtp/votca/bin/csg_call")
set_target_properties(VOTCA::csg_call PROPERTIES VOTCASHARE "/home/yoar/votca/xtp/votca/share/votca")
set_target_properties(VOTCA::csg_call PROPERTIES VOTCA_PATH "/home/yoar/votca/xtp/votca/bin")
set_target_properties(VOTCA::votca_csg PROPERTIES BINARIES "csg_boltzmann;csg_call;csg_density;csg_dlptopol;csg_dump;csg_fmatch;csg_gmxtopol;csg_imc_solve;csg_inverse;csg_map;csg_property;csg_resample;csg_reupdate;csg_stat")
